version: "3.8"
services:
  next:
    image: node:18.15-bullseye-slim
    tty: true
    command: sh -c "yarn install && yarn dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./app:/app
