version: "3.8"
services:
  wab-next:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - "./app:/app"
    # Run build & start in container
    # command: >
    #   /bin/sh -c "yarn install &&
    #               yarn build &&
    #               yarn start"
    # Run dev in container
    command: >
      /bin/sh -c "yarn install &&
                  yarn dev"
    environment:
      - WATCHPACK_POLLING=true
